name: Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest
    
    - uses: actions/setup-java@latest
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - run: chmod +x ./gradlew
    
    - run: ./gradlew clean assembleDebug --stacktrace
